### ISSUE TITLE
[bug] Function to withdraw from contract account to another account

### ISSUE THREAD

**Issue by htafolla** [near/core-contracts#24] opened 2020-05-19 13:32 UTC
There was an incident where @arn77 transferred 75k NEAR to the "contract address" via the web wallet and presently there is not a way to transfer that NEAR back to the transferring account or to another account.

Issue:
1. When using the transfer function on https://wallet.betanet.near.org "contract accounts" are showing up.
2. Once NEAR is transferred to a contract account, it should be able to be transferred back out.

What are the usecases for NEAR being transferred to a contract?
1. For gas?
2 In the case the contract itself wants to participate in staking?

**Comment by evgenykuzyakov** [comment] 2020-05-21 18:03
It's not a bug. This type of transfers should not be easily done from the wallet.
The contract has no ability to withdraw user's tokens. Even if tokens were accidentally transferred, they will be distributed as a reward to the participants of the pool

**Comment by frol** [comment] 2020-05-21 20:13
@evgenykuzyakov Do we want to prevent this common mistake of sending instead of delegating? (just reported by another user in Russian Telegram community group)

**Comment by zavodil** [comment] 2020-05-22 16:19
just experienced case when my delegation contract became useless after I sent tokens from it to the owner account. All calls of deposit function gave an error

```Scheduling a call: node.deposit() with attached 50 NEAR
Error:  GuestPanic [Error]: Smart contract panicked: panicked at &#39;The new total balance should not be less than the old total balance&#39;, src&#x2F;lib.rs:507:9```

I tried many times with different amounts.

As soon as I topped up this contract account with 300N everything became ok.

you may transactions here https://explorer.betanet.near.org/accounts/node  - lot of failed deposis before the send method https://explorer.betanet.near.org/transactions/Dg1jbQBMYibUx3Vccu49G7i2dmyhN9rr8F2XjwXK4i18

**Comment by jimmy3dita** [comment] 2020-05-25 16:20
As soon as we have the UI, this error may be less likely. I support the routing to `deposit`

**Comment by evgenykuzyakov** [comment] 2020-05-26 17:18
@zavodil You should not be able to manually use account where the contract is deployed. The action violates the requirement of not having any access keys on the staking pool.
@jimmy3dita You need to change Stake wars rules and not give tokens to accounts. Instead delegate them to the staking pools that are locked.

**Comment by jimmy3dita** [comment] 2020-06-11 18:50
> @zavodil You should not be able to manually use account where the contract is deployed. The action violates the requirement of not having any access keys on the staking pool.
> @jimmy3dita You need to change Stake wars rules and not give tokens to accounts. Instead delegate them to the staking pools that are locked.

It's pretty much how we are operating now

**Closed** 2020-06-11 21:33 UTC
